import Head from 'next/head'
import { useAuth } from '../context/AuthContext'
import { useRouter } from 'next/router'
import UserDashboard from '../components/UserDashboard'

export default function Home() {

  const {userInfo, currentUser} = useAuth()
  const router = useRouter()

  if (!currentUser) {
    router.push("/login")
  }

  if (currentUser && !currentUser.displayName) {
    router.push("/setup")
  }

  return (
    <div className='bg-gray-500 h-screen'>
      <Head>
        <title>PortFolder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentUser && currentUser.displayName && <UserDashboard/>}
    </div>
  )
}
